services:
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile
    image: cpf-management/frontend:1.0.0
    container_name: frontend
    ports:
      - "0.0.0.0:8888:80"
    restart: unless-stopped    
    networks:
      - mongo-network
    
networks:
  mongo-network:
    driver: bridge